version: '3'

volumes:
  pg_data_production_foodgram:
  static_volume_foodgram:
  media_volume_foodgram:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data_production_foodgram:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: schneidermark/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume_foodgram:/backend_static
      - media_volume_foodgram:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: schneidermark/foodgram_frontend:latest
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static_volume_foodgram:/frontend_static
  gateway:
    image: schneidermark/foodgram_gateway:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_volume_foodgram:/staticfiles/
      - media_volume_foodgram:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db