version: '3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
    restart: on-failure
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static
  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_foodgram:/staticfiles
      - media_foodgram:/media/
      - ./docs/:/staticfiles/docs/