version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: schneidermark/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: schneidermark/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: schneidermark/foodgram_gateway:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    depends_on:
      - db