version: '3'

volumes:
  pg_data_production_foodgram:
  static_volume_foodgram:
  media_volume_foodgram:

services:
  db:
    env_file: ./.env
    image: postgres:13.10
    volumes:
      - pg_data_production_foodgram:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: schneidermark/foodgram_backend:latest
    env_file: ./.env
    volumes:
      - static_volume_foodgram:/app/static/
      - media_volume_foodgram:/media/
    depends_on:
      - db
  frontend:
    env_file: ./.env
    image: schneidermark/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    image: schneidermark/foodgram_gateway:latest
    ports:
      - "8080:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - static_volume_foodgram:/var/html/static/
      - media_volume_foodgram:/media/
    depends_on:
      - db
      - backend