# Generated by Django 3.2.16 on 2024-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
