# Generated by Django 3.2.16 on 2024-04-08 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='is_in_shopping_cart', to='recipes.Recipe', verbose_name='Корзина покупок'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/recipes', verbose_name='Картинка'),
        ),
    ]
