# Generated by Django 3.2.16 on 2024-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
